version: '3.6'

services:

  django:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "gunicorn smd.wsgi --bind 0.0.0.0:8000"
    container_name: django
    image: django_image
    env_file:
      - .env
    ports:
      - '8000:8000'

  frontend:
    restart: always
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    container_name: frontend
    image: frontend_image
    depends_on:
      - django
    ports:
      - '8080:8080'
